TELEGRAM_BOT_TOKEN: ""
OPENAI_API_KEY: ""
OPENAI_CHAT_MODEL: "gpt-4"
OPENAI_TRANSCRIPT_MODEL: "whisper-1"
IMAGE_SIZE: "512x512"
CONTEXT_SIZE_BYTES: 7000
MAX_VOICE_MESSAGE_DURATION: "30s"
GOOGLE_TEXT_TO_SPEECH: ""
GOOGLE_VOICES: ""
GOOGLE_DEFAULT_VOICE: "ru-RU-Standard-B"
